trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'backend/LoggingFunctionApp/**/*.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'backend/LoggingFunctionApp/**/*.csproj'
    env:
      APPINSIGHTS_INSTRUMENTATIONKEY: $(APPINSIGHTS_INSTRUMENTATIONKEY)
