trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'backend/Authentication/**/*.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'backend/Authentication/**/*.csproj'
    env:
      DB_HOST: $(DB_HOST)
      DB_USER: $(DB_USER)
      DB_NAME: $(DB_NAME)
      DB_PORT: $(DB_PORT)
      DB_PASSWORD: $(DB_PASSWORD)
      JWT_SECRET_KEY: $(JWT_SECRET_KEY)
      AUTH_AES256_IV: $(AUTH_AES256_IV)
      AUTH_AES256_KEY: $(AUTH_AES256_KEY)
