trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - backend/UserManagement

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'backend/UserManagement/**/*.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'backend/UserManagement/**/*.csproj'
    env:
      JWT_SECRET_KEY: $(JWT_SECRET_KEY)
      DB_HOST: $(DB_HOST)
      DB_USER: $(DB_USER)
      DB_NAME: $(DB_NAME)
      DB_PORT: $(DB_PORT)
      DB_PASSWORD: $(DB_PASSWORD)
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'backend/UserManagement/src/src.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'user-dev-build'
      publishLocation: 'Container'
